### PR TITLE
Add preloading info in php.ini

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Review by nicolas-grekas — COMMENTED** [review]
Beware, I think the name changed from 4.4 to 5.1

**Comment by fabpot** [comment]
@nicolas-grekas fixed

**Comment by OskarStark** [comment]
@localheinz we should add this to our php.ini, too 👌🏻

**Comment by OskarStark** [comment]
@fabpot it looks like this does not work on SfCloud in combination with `symfony env:debug` 🤔 

Afterwards my logs are showing:
```
[app] [04-Sep-2020 06:24:13 UTC] PHP Warning:  PHP Startup: failed to open stream: No such file or directory in Unknown on line 0
[app] [04-Sep-2020 06:24:13 UTC] PHP Fatal error:  PHP Startup: Failed opening required '/app/var/cache/prod/srcApp_KernelProdContainer.preload.php' (include_path='.:') in Unknown on line 0
[app] [04-Sep-2020 06:24:14 UTC] PHP Warning:  PHP Startup: failed to open stream: No such file or directory in Unknown on line 0
[app] [04-Sep-2020 06:24:14 UTC] PHP Fatal error:  PHP Startup: Failed opening required '/app/var/cache/prod/srcApp_KernelProdContainer.preload.php' (include_path='.:') in Unknown on line 0
[app] [04-Sep-2020 06:24:15 UTC] PHP Warning:  PHP Startup: failed to open stream: No such file or directory in Unknown on line 0
[app] [04-Sep-2020 06:24:15 UTC] PHP Fatal error:  PHP Startup: Failed opening required '/app/var/cache/prod/srcApp_KernelProdContainer.preload.php' (include_path='.:') in Unknown on line 0
[app] [04-Sep-2020 06:24:16 UTC] PHP Warning:  PHP Startup: failed to open stream: No such file or directory in Unknown on line 0
[app] [04-Sep-2020 06:24:16 UTC] PHP Fatal error:  PHP Startup: Failed opening required '/app/var/cache/prod/srcApp_KernelProdContainer.preload.php' (include_path='.:') in Unknown on line 0
[app] [04-Sep-2020 06:24:17 UTC] PHP Warning:  PHP Startup: failed to open stream: No such file or directory in Unknown on line 0
[app] [04-Sep-2020 06:24:17 UTC] PHP Fatal error:  PHP Startup: Failed opening required '/app/var/cache/prod/srcApp_KernelProdContainer.preload.php' (include_path='.:') in Unknown on line 0
```

**Comment by OskarStark** [comment]
We had to remove the setting, we had some strange side effects:
Bildschirmfoto 2020-09-04 um 08 35 53

and it looks like FPM died:
Bildschirmfoto 2020-09-04 um 08 36 37

If you need some help to investigate, we can provide a "failing environment"

**Comment by nicolas-grekas** [comment]
That's for bugs.php.net...

**Comment by nicolas-grekas** [comment]
About the warnings in your first screenshot @OskarStark, you should investigate them, that's possibly on your side to fix.

**Comment by OskarStark** [comment]
Will do, thanks

**Comment by fabpot** [comment]
See 1656fdb9875d6459512a62c794f15c7add6dd4fa for an update of the default values.

**Pull request merged**
